spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/dev
  profiles:
     active: native
  security:
    user:
      password: password

server:
  port: 8888

