---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-monitor
  labels:
    app: rabbitmq
  namespace: piggymetrics
spec:
  endpoints:
    - honorLabels: false
      interval: 15s
      path: /metrics
      port: monotir
      scheme: http
  selector:
    matchLabels:
      project: piggymetrics
