version: '2.1'
services:
  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    ports:
      - 25000:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"  
  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    ports:
      - 27000:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10" 
  notification-mongodb:
    image: sqshq/piggymetrics-mongodb
    ports:
      - 28000:27017
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"
