security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: root
      accessTokenUri: http://10.103.1.36:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 10.103.1.54
      username: user
      password: root
      database: piggymetrics
      port: 26000

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true