security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://127.0.0.1:5000/uaa/oauth/token
#      grant-type: client_credentials
      scope: server

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 127.0.0.1
      database: account
      port: 27017
  rabbitmq:
    host: 127.0.0.1
    username: dev
    port: 5672
    password: msm8996z2131

server:
  servlet:
    context-path: /accounts

feign:
  hystrix:
    enabled: true