security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: root
      accessTokenUri: http://10.103.1.36:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 10.103.1.54
      username: user
      password: root
      database: piggymetrics
      port: 27000

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io