security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://127.0.0.1:5000/uaa/oauth/token
#      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: statistics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io